version: "3"
services:
  zookeeper-01:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ./zookeeper-01/conf:/opt/zookeeper/conf
      - ./zookeeper-01/data:/opt/zookeeper/data
    ports:
      - 2181:2181
  zookeeper-02:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ./zookeeper-02/conf:/opt/zookeeper/conf
      - ./zookeeper-02/data:/opt/zookeeper/data
    ports:
      - 2182:2181
  zookeeper-03:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ./zookeeper-03/conf:/opt/zookeeper/conf
      - ./zookeeper-03/data:/opt/zookeeper/data
    ports:
      - 2183:2181
  zookeeper:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ./zookeeper/conf:/opt/zookeeper/conf
      - ./zookeeper/data:/opt/zookeeper/data
    ports:
      - 2182:2181
  kafka-01:
    image: kafka:2.1.1
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./kafka-01/config:/opt/kafka/config
      - ./kafka-01/kafka-logs:/tmp/kafka-logs
      - ./kafka-01/logs:/opt/kafka/logs
    environment:
      - JMX_PORT=9991
    ports: 
      - 9091:9092
      - 9991:9991  
  kafka-02:
    image: kafka:2.1.1
    deploy:
      resources:
        limits:
          memory: 512M    
    volumes:
      - ./kafka-02/config:/opt/kafka/config
      - ./kafka-02/kafka-logs:/tmp/kafka-logs
      - ./kafka-02/logs:/opt/kafka/logs
    environment:
      - JMX_PORT=9992     
    ports: 
      - 9092:9092
      - 9992:9992      
  kafka-03:
    image: kafka:2.1.1
    deploy:
      resources:
        limits:
          memory: 512M    
    volumes:
      - ./kafka-03/config:/opt/kafka/config
      - ./kafka-03/kafka-logs:/tmp/kafka-logs
      - ./kafka-03/logs:/opt/kafka/logs
    environment:
      - JMX_PORT=9993
    ports: 
      - 9093:9092
      - 9993:9993
  kafka-manager:
    image: hlebalbau/kafka-manager:2.0.0.2
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      - KAFKA_MANAGER_AUTH_ENABLED=true
      - KAFKA_MANAGER_USERNAME=admin
      - KAFKA_MANAGER_PASSWORD=admin
      - APPLICATION_SECRET=random-secret