version: "3"
services:
  zookeeper-01:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    environment: 
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-01:2281:2381 server.2=zookeeper-02:2281:2381 server.3=zookeeper-03:2281:2381
    ports:
      - 2181:2181
  zookeeper-02:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    environment: 
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-01:2281:2381 server.2=zookeeper-02:2281:2381 server.3=zookeeper-03:2281:2381
    ports:
      - 2182:2181
  zookeeper-03:
    image: zookeeper:3.4.10
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-01:2281:2381 server.2=zookeeper-02:2281:2381 server.3=zookeeper-03:2281:2381
    ports:
      - 2183:2181      
  kafka-01:
    image: fanhaodong/kafka:2.1.1
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      JMX_PORT: 9291
    ports:
      - 9191:9191
      - 9291:9291
    volumes: 
      - ./kafka-01/config:/opt/kafka/config
      - ./kafka-01/data:/tmp/kafka-logs
  kafka-02:
    image: fanhaodong/kafka:2.1.1
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      JMX_PORT: 9292
    ports:
      - 9192:9192
      - 9292:9292
    volumes:
      - ./kafka-02/config:/opt/kafka/config
      - ./kafka-02/data:/tmp/kafka-logs
  kafka-03:
    image: fanhaodong/kafka:2.1.1
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      JMX_PORT: 9293
    ports:
      - 9193:9193
      - 9293:9293
    volumes:
      - ./kafka-03/config:/opt/kafka/config
      - ./kafka-03/data:/tmp/kafka-logs
  kafka-manager:
    image: hlebalbau/kafka-manager:2.0.0.2
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin